//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIBBDApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Address()
        {
            this.Driver = new HashSet<Driver>();
            this.TheftFoundedCar = new HashSet<TheftFoundedCar>();
        }
    
        public int AddressID { get; set; }
        public Nullable<int> PostCode { get; set; }
        public int Region { get; set; }
        public Nullable<int> City { get; set; }
        public Nullable<int> Street { get; set; }
        public string House { get; set; }
    
        public virtual City City1 { get; set; }
        public virtual Region Region1 { get; set; }
        public virtual Street Street1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Driver> Driver { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TheftFoundedCar> TheftFoundedCar { get; set; }
    }
}
