//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIBBDApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class DriverLicense
    {
        public int LisenseID { get; set; }
        public int LicensetSeries { get; set; }
        public int LicensetNum { get; set; }
        public int LicenseIssueOrg { get; set; }
        public int LicneseDriver { get; set; }
    
        public virtual DocumentsIssueOrganization DocumentsIssueOrganization { get; set; }
        public virtual Driver Driver { get; set; }
    }
}
