//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIBBDApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GIBDD_Suv_DorEntities : DbContext
    {
        public GIBDD_Suv_DorEntities()
            : base("name=GIBDD_Suv_DorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Address { get; set; }
        public virtual DbSet<Brand> Brand { get; set; }
        public virtual DbSet<Car> Car { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<DocumentsIssueOrganization> DocumentsIssueOrganization { get; set; }
        public virtual DbSet<Driver> Driver { get; set; }
        public virtual DbSet<Driver_Insurance> Driver_Insurance { get; set; }
        public virtual DbSet<DriverLicense> DriverLicense { get; set; }
        public virtual DbSet<Insurance> Insurance { get; set; }
        public virtual DbSet<InsuranceCompany> InsuranceCompany { get; set; }
        public virtual DbSet<Model> Model { get; set; }
        public virtual DbSet<OrgName> OrgName { get; set; }
        public virtual DbSet<OwnerChangeHistory> OwnerChangeHistory { get; set; }
        public virtual DbSet<Passport> Passport { get; set; }
        public virtual DbSet<Region> Region { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Street> Street { get; set; }
        public virtual DbSet<TheftFoundedCar> TheftFoundedCar { get; set; }
        public virtual DbSet<VehiclePassport> VehiclePassport { get; set; }
    }
}
