//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIBBDApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TheftFoundedCar
    {
        public int CaseID { get; set; }
        public int CaseCar { get; set; }
        public System.DateTime CaseDate { get; set; }
        public int CaseAddress { get; set; }
        public int CaseStatus { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Car Car { get; set; }
        public virtual Status Status { get; set; }
    }
}
